insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRAAHILCOVIDDGKHAN-101','Sarah','Khan','Father',  '1998-3-10', 'Rawalpindi', 'A +ve', 'xyz','abc','a','b','c','Punjab', 'd','MBA','+923330959320','051-2329299', 'sarahkhansadozai@gmail.com','Islamabad','Female','','DC-123','Aahil','Orthopedic');
insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRALIYANCOVIDMULTAN-102','Ayesha','Khan', 'Father', '3-22-2000','Lahore',  'AB +ve','xyz','abc','a', 'b','c','Punjab', 'd','BBA','+933361922198','051-23292919','ayeshakhansadozai@gmail.com','Rawalpindi','Female','','DC-456','Aleha','Pathology');
insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRALEHACOVIDOKARA-103','Naila','Farooq', 'Husband', '12-19-1995','Karachi',  'O +ve','xyz', 'abc','a','b','c','Sindh', 'd','Computer Engineer', '+923321551303','051-2329239','hari@gmail.com','Lahore','Female','','DC-789','Aaniat','Gynacology');
insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRAANIATCOVIDLHR-104','Maryam', 'Shumail','Husband', '5-2-2004','Islamabad', 'B +ve','xyz', 'abc', 'a','b','c','Punjab', 'd','Software Engineer','+923455080502','051-2329249','arsalan@gmail.com','Karachi','Female','','DC-321','Ayan','Isolation ward');
insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRAHMADCOVIDKHI-105','Rabail', 'Shumail','Father', '8-4-2011', 'Rawalpindi', 'AB -ve', 'xyz','abc','a', 'b','c','Sindh', 'd','MBBS','+923335176267','051-2329259','shahzaib@gmail.com','Multan','Female','','DC-654','Alyan','Cancer Department');
insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRAYANCOVIDISB-106','Naimal','Fatima', 'Father','5-10-2019','Islamabad',  'O -ve', 'xyz', 'abc','a', 'b','c','Fedral', 'd','LLB','+923335176265','051-2329279','wardah@gmail.com','Islamabad','Female','','DC-987','Ahmad','Dental');
insert into patient( MR_no, CNIC, pt_first_name, pt_last_name, father_or_husband, DOB, place_of_birth, blood_type, present_address, permanent_address, district, tehsil, state, caste, qualification, mobile_no, landline_no, email, city, gender, image, Dc_no, dr_name, dept_name)
values('PTDRZILAYLCOVIDRWP-107','Sakeena',' Begum', 'Husband','10-10-1992','Rawalpindi', 'A +ve', 'xyz', 'abc','a', 'b','c','Punjab', 'd','HND', '+923029548711','051-2329269','huraira@gmail.com','Rawalpindi','Female','','DC-3110','Zilay','Cardiology');