//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int id { get; set; }
        public Nullable<int> Ward_no { get; set; }
        public Nullable<int> Bed_no { get; set; }
        public int doctor_id { get; set; }
        public string MR_no { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
