//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.Hospitals = new HashSet<Hospital>();
            this.recovered_patient = new HashSet<recovered_patient>();
        }
    
        public string MR_no { get; set; }
        public string CNIC { get; set; }
        public string pt_first_name { get; set; }
        public string pt_last_name { get; set; }
        public string father_or_husband { get; set; }
        public string DOB { get; set; }
        public string place_of_birth { get; set; }
        public string blood_type { get; set; }
        public string present_address { get; set; }
        public string permanent_address { get; set; }
        public string mobile_no { get; set; }
        public string landline_no { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string test { get; set; }
        public string symptom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospital> Hospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recovered_patient> recovered_patient { get; set; }
        public virtual symptom symptom1 { get; set; }
    }
}
