//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid
{
    using System;
    using System.Collections.Generic;
    
    public partial class recovered_patient
    {
        public int pd_no { get; set; }
        public Nullable<System.DateTime> date_of_discharge { get; set; }
        public string plasme_donor_name { get; set; }
        public string MR_number { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
