//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid
{
    using System;
    using System.Collections.Generic;
    
    public partial class symptom
    {
        public string MR_no { get; set; }
        public string drycough { get; set; }
        public string headache { get; set; }
        public string fever { get; set; }
        public string vomiting { get; set; }
        public string chest_pain { get; set; }
        public string loss_of_smell { get; set; }
        public string shortness_of_breath { get; set; }
        public string loss_of_taste { get; set; }
        public string fatigue { get; set; }
        public string diarrhea { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
